name: Build
on: [ push, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ij: [ 2021.1.3, 2022.2.1 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build and verify
        run: ./gradlew clean buildPlugin test verifyPlugin -PpluginIdeaVersion=IU-${{ matrix.ij }} --warning-mode all

